spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/satishchandra-maurya/configuration_properties
          clone-on-start: true

management:
  security:
    enabled: false
          
